### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by ttrodrigz** [stevenpawley/recipeselectors#6]
No real issue here, just checking to see if this package is still being developed and if there are plans to "fully" bring it into the tidymodels family. Finding the various `step_select_*()` functions to be very helpful, but apprehensive to use them for production code since it looks like the last commit was a couple years ago and the package is not on CRAN yet. Thanks for all the effort that's gone into it so far.

**Comment by stevenpawley** [comment]
Hi! That's a good question. It is still in development, but there has been a bit of a hiatus while I've been working on other projects. However, I'm starting to need feature selection again in some of my own work, so I'm going to be cleaning things up and submitting an initial version to CRAN within the next month or so, specifically to just get a simple version out there for production purposes. We are looking to add an additional step for fast correlation based filtering, and I'm also planning to split the 'step_select_vip' into a few specific methods, something like 'step_select_trees' and 'step_select_glm' (with an 'engine' parameter) which is a bit less flexible, but will match the general tidymodels approach and will allow tuning of the model parameters, rather than just shoving a parsnip model into the step.

**Comment by ttrodrigz** [comment]
Hi Stephen, that sounds great. I'm using these recipe selectors a lot for a couple projects so I'd be happy to test things out once you've added the new features.
